name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Build
        run: |
          flyctl deploy \
            --remote-only \
            --build-only \
            --build-secret INFURA_API_KEY=${{ secrets.INFURA_API_KEY }} \
            --build-secret ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }} \
            --build-secret PASSPORT_API_KEY=${{ secrets.PASSPORT_API_KEY }} \
            --build-secret PASSPORT_SCORER_ID=${{ secrets.PASSPORT_SCORER_ID }} \
            --build-secret COINGECKO_API_KEY=${{ secrets.COINGECKO_API_KEY }} \
            --build-secret IPFS_GATEWAY=${{ secrets.IPFS_GATEWAY }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy
        run: |
          flyctl deploy \
            --remote-only \
            --build-secret INFURA_API_KEY=${{ secrets.INFURA_API_KEY }} \
            --build-secret ALCHEMY_API_KEY=${{ secrets.ALCHEMY_API_KEY }} \
            --build-secret PASSPORT_API_KEY=${{ secrets.PASSPORT_API_KEY }} \
            --build-secret PASSPORT_SCORER_ID=${{ secrets.PASSPORT_SCORER_ID }} \
            --build-secret COINGECKO_API_KEY=${{ secrets.COINGECKO_API_KEY }} \
            --build-secret IPFS_GATEWAY=${{ secrets.IPFS_GATEWAY }}
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
